/**
 * OpenClaw config and Docker env/compose generation.
 * See ProductPlan.md — OpenClaw Configuration Generated, Docker Compose Template.
 */

import type { LLMProvider, Channel } from "./types.js";

const OPENCLAW_VERSION_DEFAULT = "2026.2.6-3";

/** Template name for configs (e.g. anthropic-telegram). */
export function getConfigTemplateName(
  llmProvider: LLMProvider,
  channel: Channel
): string {
  return `${llmProvider}-${channel}`;
}

/** Substitute ${VAR} placeholders in a template string. */
export function substituteVars(
  content: string,
  vars: Record<string, string>
): string {
  let out = content;
  for (const [key, value] of Object.entries(vars)) {
    out = out.replace(new RegExp(`\\\$\\{${key}\\}`, "g"), value ?? "");
  }
  return out;
}

/** Variables used in OpenClaw config templates. */
export interface OpenClawConfigVars {
  OPENCLAW_GATEWAY_TOKEN: string;
  LLM_API_KEY: string;
  CHANNEL_TOKEN: string;
  DM_POLICY: string;
  /** Telegram allowFrom JSON array of user IDs, e.g. "[]" */
  ALLOW_FROM?: string;
}

/**
 * Render OpenClaw config JSON from template content and vars.
 * Caller loads template from templates/configs/<llm>-<channel>.json5.
 */
export function renderOpenClawConfig(
  templateContent: string,
  vars: OpenClawConfigVars
): string {
  const all: Record<string, string> = {
    ...vars,
    ALLOW_FROM: vars.ALLOW_FROM ?? "[]",
  };
  return substituteVars(templateContent, all);
}

/** Generate Docker Compose .env file content. */
export function renderEnvFile(vars: { OPENCLAW_GATEWAY_TOKEN: string; OPENCLAW_VERSION?: string }): string {
  const version = vars.OPENCLAW_VERSION ?? OPENCLAW_VERSION_DEFAULT;
  return `OPENCLAW_GATEWAY_TOKEN=${vars.OPENCLAW_GATEWAY_TOKEN}
OPENCLAW_VERSION=${version}
`;
}

/** Docker Compose YAML template (minimal; matches ProductPlan). */
const DOCKER_COMPOSE_TEMPLATE = `# Generated by HoldMyClaw
services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:\${OPENCLAW_VERSION:-2026.2.6-3}
    container_name: openclaw-gateway
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: \${OPENCLAW_GATEWAY_TOKEN}
    volumes:
      - ./config:/home/node/.openclaw
      - ./workspace:/home/node/.openclaw/workspace
    ports:
      - "\${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "\${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      - "node"
      - "dist/index.js"
      - "gateway"
      - "--bind"
      - "\${OPENCLAW_GATEWAY_BIND:-lan}"
      - "--port"
      - "18789"

  openclaw-cli:
    image: ghcr.io/openclaw/openclaw:\${OPENCLAW_VERSION:-2026.2.6-3}
    container_name: openclaw-cli
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: \${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
    volumes:
      - ./config:/home/node/.openclaw
      - ./workspace:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
    profiles: ["cli"]
`;

/** Get Docker Compose YAML for local or cloud (same file; bind differs via env). */
export function getDockerComposeYaml(): string {
  return DOCKER_COMPOSE_TEMPLATE;
}

export { OPENCLAW_VERSION_DEFAULT };
