# Product Definition
# See ProductPlan.md for full context.
schema_version: 1
name: holdmyclaw
tagline: "Deploy OpenClaw in 5 minutes. Your server, your data, completely free."
description: |
  HoldMyClaw is a free setup wizard that deploys OpenClaw on your own cloud server
  (Hetzner, DigitalOcean) or locally with Docker. We configure everything, hand you
  the keys, and walk away. You own everything; we manage nothing. Not a business —
  a community tool that builds goodwill and distribution.

  Domain: holdmyclaw.com (registered).
vision: |
  Make OpenClaw setup trivially easy for everyone. Free, no subscription, no lock-in.
  User owns server, data, and API keys. We teach them to manage it themselves.
principles:
  - "You own everything — your server, your data, your API keys. We never touch it after setup."
  - "Free — no subscription, no hidden fees, no payment required. Ever."
  - "We teach, not trap — you get a guide to manage it yourself. We want you to NOT need us."
  - "No lock-in — if we disappear tomorrow, your agent keeps running."
  - "Community-first — we exist to help, not to extract rent."
okrs: []
target_users:
  - "Technical users who want a fast, reproducible OpenClaw setup"
  - "Non-technical users who can follow a step-by-step wizard"
  - "Self-hosters who want to own their AI agent and data"
created_at: "2026-02-07"
updated_at: "2026-02-07"
