# Product Definition
schema_version: 1
name: holdmyclaw
tagline: ""
description: Add your product description here.
vision: ""
principles: []
okrs: []
target_users: []
created_at: 2026-02-07
updated_at: 2026-02-07
